Repository stolostron/multiclusterhub-repo, pull requests merged in 2021-06, with the labels that each got.

#421 Update console chart version to 2.0.2
  cicd-scripts/chartSHA.csv
  multiclusterhub/charts/application-chart-1.0.0.tgz
  multiclusterhub/charts/cert-manager-3.6.1.tgz
  multiclusterhub/charts/cert-manager-webhook-3.6.1.tgz
  multiclusterhub/charts/configmap-watcher-3.6.0.tgz
  multiclusterhub/charts/console-chart-2.0.1.tgz
  multiclusterhub/charts/console-chart-2.0.2.tgz
  multiclusterhub/charts/grc-2.0.0.tgz
  multiclusterhub/charts/index.yaml
  multiclusterhub/charts/kui-web-terminal-3.6.0.tgz
  multiclusterhub/charts/management-ingress-3.4.0.tgz
  multiclusterhub/charts/rcm-2.0.2.tgz
  multiclusterhub/charts/search-prod-3.5.1.tgz
  multiclusterhub/charts/topology-1.0.0.tgz
Labels: lgtm

#422 prep for DCO signoff
  .github/workflows/update-charts.yml
  CONTRIBUTING.md
Labels: approved, lgtm

#424 Update to version 2.2.5
  CHART_VERSION
  multiclusterhub/charts/application-chart-2.2.4.tgz
  multiclusterhub/charts/application-chart-2.2.5.tgz
  multiclusterhub/charts/cert-manager-2.2.4.tgz
  multiclusterhub/charts/cert-manager-2.2.5.tgz
  multiclusterhub/charts/cert-manager-webhook-2.2.4.tgz
  multiclusterhub/charts/cert-manager-webhook-2.2.5.tgz
  multiclusterhub/charts/configmap-watcher-2.2.4.tgz
  multiclusterhub/charts/configmap-watcher-2.2.5.tgz
  multiclusterhub/charts/console-chart-2.2.4.tgz
  multiclusterhub/charts/console-chart-2.2.5.tgz
  multiclusterhub/charts/grc-2.2.4.tgz
  multiclusterhub/charts/grc-2.2.5.tgz
  multiclusterhub/charts/index.yaml
  multiclusterhub/charts/kui-web-terminal-2.2.4.tgz
  multiclusterhub/charts/kui-web-terminal-2.2.5.tgz
  multiclusterhub/charts/management-ingress-2.2.4.tgz
  multiclusterhub/charts/management-ingress-2.2.5.tgz
  multiclusterhub/charts/rcm-2.2.4.tgz
  multiclusterhub/charts/rcm-2.2.5.tgz
  multiclusterhub/charts/search-prod-2.2.4.tgz
  multiclusterhub/charts/search-prod-2.2.5.tgz
  multiclusterhub/charts/topology-2.2.4.tgz
  multiclusterhub/charts/topology-2.2.5.tgz
Labels: dco-signoff: no

#427 start signing off for dco
  cicd-scripts/build.sh
  cicd-scripts/chartAutomation.sh
Labels: approved, dco-signoff: yes, lgtm

#428 Update chartAutomation.sh
  cicd-scripts/chartAutomation.sh
Labels: dco-signoff: no, lgtm

#431 adding dco support to 2.1 automation
  cicd-scripts/build.sh
  cicd-scripts/chartAutomation.sh
  multiclusterhub/charts/application-chart-2.1.8.tgz
  multiclusterhub/charts/cert-manager-2.1.8.tgz
  multiclusterhub/charts/cert-manager-webhook-2.1.8.tgz
  multiclusterhub/charts/configmap-watcher-2.1.8.tgz
  multiclusterhub/charts/console-chart-2.1.8.tgz
  multiclusterhub/charts/grc-2.1.8.tgz
  multiclusterhub/charts/index.yaml
  multiclusterhub/charts/kui-web-terminal-2.1.8.tgz
  multiclusterhub/charts/management-ingress-2.1.8.tgz
  multiclusterhub/charts/rcm-2.1.8.tgz
  multiclusterhub/charts/search-prod-2.1.8.tgz
  multiclusterhub/charts/topology-2.1.8.tgz
Labels: approved, dco-signoff: yes, lgtm

#433 Update to version 2.2.6
  CHART_VERSION
  multiclusterhub/charts/application-chart-2.2.5.tgz
  multiclusterhub/charts/application-chart-2.2.6.tgz
  multiclusterhub/charts/cert-manager-2.2.5.tgz
  multiclusterhub/charts/cert-manager-2.2.6.tgz
  multiclusterhub/charts/cert-manager-webhook-2.2.5.tgz
  multiclusterhub/charts/cert-manager-webhook-2.2.6.tgz
  multiclusterhub/charts/configmap-watcher-2.2.5.tgz
  multiclusterhub/charts/configmap-watcher-2.2.6.tgz
  multiclusterhub/charts/console-chart-2.2.5.tgz
  multiclusterhub/charts/console-chart-2.2.6.tgz
  multiclusterhub/charts/grc-2.2.5.tgz
  multiclusterhub/charts/grc-2.2.6.tgz
  multiclusterhub/charts/index.yaml
  multiclusterhub/charts/kui-web-terminal-2.2.5.tgz
  multiclusterhub/charts/kui-web-terminal-2.2.6.tgz
  multiclusterhub/charts/management-ingress-2.2.5.tgz
  multiclusterhub/charts/management-ingress-2.2.6.tgz
  multiclusterhub/charts/rcm-2.2.5.tgz
  multiclusterhub/charts/rcm-2.2.6.tgz
  multiclusterhub/charts/search-prod-2.2.5.tgz
  multiclusterhub/charts/search-prod-2.2.6.tgz
  multiclusterhub/charts/topology-2.2.5.tgz
  multiclusterhub/charts/topology-2.2.6.tgz
Labels: dco-signoff: yes, lgtm
